SystemeGestionCourier/Models/Courrier.cs
using System;
using System.Collections.Generic;

namespace SystemGestionCourier.Models
{
    public class Courrier
    {
        public int ID { get; set; }
        public string Sujet { get; set; }
        public string Expiditeur { get; set; }
        public string Destinataire { get; set; }
        public string Message { get; set; }
        public DateTime CourDate { get; set; }

        public String Type { get; set; }
    }
}

SystemeGestionCourier/Controllers/CourrierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemGestionCourier.Models;
using SystemeGestionCourier.DAL;
using System.Text;
using System.IO;
using System.Data.OleDb;
using System.Configuration;
using System.Xml;
using System.Data.SqlClient;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;

namespace SystemeGestionCourier.Controllers
{
    public class CourrierController : Controller
    {
        public CourrierContext db = new CourrierContext();

        // GET: /Courrier/
        public ActionResult Index()
        {
            return View(db.Courrier.ToList());
        }

        // GET: /Courrier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courrier courrier = db.Courrier.Find(id);
            if (courrier == null)
            {
                return HttpNotFound();
            }
            return View(courrier);
        }

        // GET: /Courrier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Courrier/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Sujet,Expiditeur,Destinataire,Message,CourDate,TypeId")] Courrier courrier)
        {
            if (ModelState.IsValid)
            {
                db.Courrier.Add(courrier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(courrier);
        }

        // GET: /Courrier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courrier courrier = db.Courrier.Find(id);
            if (courrier == null)
            {
                return HttpNotFound();
            }
            return View(courrier);
        }

        // POST: /Courrier/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Sujet,Expiditeur,Destinataire,Message,CourDate,TypeId")] Courrier courrier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courrier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(courrier);
        }

        // GET: /Courrier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courrier courrier = db.Courrier.Find(id);
            if (courrier == null)
            {
                return HttpNotFound();
            }
            return View(courrier);
        }

        // POST: /Courrier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courrier courrier = db.Courrier.Find(id);
            db.Courrier.Remove(courrier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        /**************Import from Excel*********************/

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {

            DataSet ds = new DataSet();

            if (Request.Files["file"].ContentLength > 0)
            {
                string fileExtension = System.IO.Path.GetExtension(Request.Files["file"].FileName);

                if (fileExtension == ".xls" || fileExtension == ".xlsx")
                {
                    string FileName = System.IO.Path.GetFileName(Request.Files["file"].FileName);

                    string FolderPath = ConfigurationManager.AppSettings["FolderPath"];



                    string fileLocation = Server.MapPath(FolderPath + FileName);
                    //string fileLocation = Server.MapPath("~/Content/") + Request.Files["file"].FileName;
                    if (System.IO.File.Exists(fileLocation))
                    {

                        System.IO.File.Delete(fileLocation);
                    }
                    Request.Files["file"].SaveAs(fileLocation);
                    string excelConnectionString = string.Empty;
                    excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    //connection String for xls file format.
                    if (fileExtension == ".xls")
                    {
                        excelConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                    }
                    //connection String for xlsx file format.
                    else if (fileExtension == ".xlsx")
                    {

                        excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    }
                    //Create Connection to Excel work book and add oledb namespace
                    OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                    excelConnection.Open();
                    DataTable dt = new DataTable();

                    dt = excelConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                    if (dt == null)
                    {
                        return null;
                    }

                    String[] excelSheets = new String[dt.Rows.Count];
                    int t = 0;
                    //excel data saves in temp file here.
                    foreach (DataRow row in dt.Rows)
                    {
                        excelSheets[t] = row["TABLE_NAME"].ToString();
                        t++;
                    }
                    OleDbConnection excelConnection1 = new OleDbConnection(excelConnectionString);


                    string query = string.Format("Select * from [{0}]", excelSheets[0]);
                    using (OleDbDataAdapter dataAdapter = new OleDbDataAdapter(query, excelConnection1))
                    {
                        dataAdapter.Fill(ds);
                    }
                }
                if (fileExtension.ToString().ToLower().Equals(".xml"))
                {
                    string fileLocation = Server.MapPath("~/Content/") + Request.Files["FileUpload"].FileName;
                    if (System.IO.File.Exists(fileLocation))
                    {
                        System.IO.File.Delete(fileLocation);
                    }

                    Request.Files["FileUpload"].SaveAs(fileLocation);
                    XmlTextReader xmlreader = new XmlTextReader(fileLocation);
                    // DataSet ds = new DataSet();
                    ds.ReadXml(xmlreader);
                    xmlreader.Close();
                }

                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    /* string conn = ConfigurationManager.ConnectionStrings["dbconnection"].ConnectionString;
                     SqlConnection con = new SqlConnection(conn);
                       string query = "Insert into Person(Name,Email,Mobile) Values('" + ds.Tables[0].Rows[i][0].ToString() + "','" + ds.Tables[0].Rows[i][1].ToString() + "','" + ds.Tables[0].Rows[i][2].ToString() + "')";
                       con.Open();
                       SqlCommand cmd = new SqlCommand(query, con);
                       cmd.ExecuteNonQuery();
                       con.Close();*/
                    Courrier messages = new Courrier { Sujet = ds.Tables[0].Rows[i][0].ToString(), Destinataire = ds.Tables[0].Rows[i][1].ToString(), Expiditeur = ds.Tables[0].Rows[i][2].ToString(), Message = ds.Tables[0].Rows[i][3].ToString(), CourDate = DateTime.Parse(ds.Tables[0].Rows[i][4].ToString()), Type = ds.Tables[0].Rows[i][5].ToString() };
                    db.Courrier.Add(messages);
                    db.SaveChanges();

                }


            }
            return RedirectToAction("Index");
        }

        /**************Import from XML*********************/

       [HttpPost]
        public ActionResult Uploadxml(HttpPostedFileBase file)
        {


            if (Request.Files["file"].ContentLength > 0)
            {
                DataSet ds = new DataSet();


                string extension = System.IO.Path.GetExtension(Request.Files["file"].FileName);


                if (extension.ToString().ToLower().Equals(".xml"))
                {
                    string fileLocation = Server.MapPath("~/Content/") + Request.Files["file"].FileName;
                    if (System.IO.File.Exists(fileLocation))

SystemeGestionCourier/Controllers/ReportsController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemeGestionCourier.DAL;

namespace SystemeGestionCourier.Controllers
{
    public class ReportsController : Controller
    {
        private readonly CourrierContext _db = new CourrierContext();


        //
        // GET: /Reports/
        public ActionResult CrystalReport1()
        {
            
            var reportPath = Server.MapPath("~/ReportTemplates/CrystalReport1.rpt");
            var customer = _db.Courrier;
           using (var ReportDocument = new ReportDocument())
            {
               
                ReportDocument.Load(reportPath);
                ReportDocument.SetDataSource(customer);
               /* var response = System.Web.HttpContext.Current.Response;
                  ReportDocument.ExportToHttpResponse(ExportFormatType.PortableDocFormat, response, true, "CrystalReport1");
               */

            }
            return new EmptyResult();
        }
	}
}

SystemeGestionCourier/Views/Courrier/Create.cshtml
@model SystemGestionCourier.Models.Courrier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Courrier</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Sujet, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sujet)
                @Html.ValidationMessageFor(model => model.Sujet)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expiditeur, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expiditeur)
                @Html.ValidationMessageFor(model => model.Expiditeur)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destinataire, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destinataire)
                @Html.ValidationMessageFor(model => model.Destinataire)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message)
                @Html.ValidationMessageFor(model => model.Message)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourDate)
                @Html.ValidationMessageFor(model => model.CourDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SystemeGestionCourier/Views/Courrier/Delete.cshtml
@model SystemGestionCourier.Models.Courrier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Courrier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sujet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sujet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expiditeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expiditeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destinataire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destinataire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SystemeGestionCourier/Views/Courrier/Details.cshtml
@model SystemGestionCourier.Models.Courrier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Courrier</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sujet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sujet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expiditeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expiditeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destinataire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destinataire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SystemeGestionCourier/Views/Courrier/Edit.cshtml
@model SystemGestionCourier.Models.Courrier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Courrier</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Sujet, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sujet)
                @Html.ValidationMessageFor(model => model.Sujet)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expiditeur, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expiditeur)
                @Html.ValidationMessageFor(model => model.Expiditeur)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destinataire, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destinataire)
                @Html.ValidationMessageFor(model => model.Destinataire)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message)
                @Html.ValidationMessageFor(model => model.Message)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourDate)
                @Html.ValidationMessageFor(model => model.CourDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SystemeGestionCourier/Views/Courrier/Index.cshtml
<script type="text/javascript" src="../../jspdf.js"></script>
<script language="javascript">
  


    ///////////////PDF/////////////////////

    function htmltopdf() {
        var pdf = new jsPDF('p', 'pt', 'letter');
        source = $('#PrintDiv')[0]; //table Id
        specialElementHandlers = {
            '#bypassme': function (element, renderer) {
                return true
            }
        };
        margins = { //table margins and width
            top: 80,
            bottom: 60,
            left: 40,
            width: 522
        };
        pdf.fromHTML(
        source,
        margins.left,
        margins.top, {
            'width': margins.width,
            'elementHandlers': specialElementHandlers
        },

        function (dispose) {
            pdf.save('Data.pdf'); //Filename
        }, margins);
    }

    ///////////////////////////Excel//////////////////////////
    var tableToExcel = (function () {
        var uri = 'data:application/vnd.ms-excel;base64,', template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>', base64 = function (
                s) {
            return window.btoa(unescape(encodeURIComponent(s)))
        }, format = function (s, c) {
            return s.replace(/{(\w+)}/g, function (m, p) {
                return c[p];
            })
        }
        return function (table, name) {
            if (!table.nodeType)
                table = document.getElementById(table);
            var cln = table.cloneNode(true);
            var paras = cln.getElementsByClassName('ignore');

            while (paras[0]) {
                paras[0].parentNode.removeChild(paras[0]);
            }
            var ctx = {
                worksheet: name || 'Worksheet',
                table: cln.innerHTML
            }
            window.location.href = uri + base64(format(template, ctx))
        }
    })();
</script>




@model IEnumerable<SystemGestionCourier.Models.Courrier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div id="PrintDiv">
    <asp:DataList ID="DataList1" runat="server">
        <table id="exportPDF" border="1" style="border-collapse: collapse;" class="table table-striped">
            <tr id="bypassme">
                <th>
                    @Html.DisplayNameFor(model => model.Sujet)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Expiditeur)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Destinataire)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Message)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th class="ignore"></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sujet)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Expiditeur)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Destinataire)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td class="ignore">
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </asp:DataList>
</div>

<button onclick="javascript:htmltopdf();">Export PDF</button>
<input type="button" onclick="tableToExcel('PrintDiv', 'W3C Example Table')" value="Export to Excel" />

<h2>Import from Excel</h2>
<div>
    @using (Html.BeginForm("Index", "Courrier", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input name="file" type="file" /><input type="submit" value="Importer" title="Upload file" />
    }
</div>

<h2>Import from XML</h2>
<div>
    @using (Html.BeginForm("Uploadxml", "Courrier", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input name="file" type="file" /><input type="submit" value="Importer" title="Upload file" />
    }
</div>
 @Html.ActionLink("Print My Report", "CrystalReport1", "Reports") 
<div>

</div>
